TIMING
    // Starter timing set. Tune the phases for the DUT before real runs.
    TS0 { PRD: 20, NRZ: 1, NRZ_BASE: 0, RZ: 8, RZ_RETURN: 10, RZ_BASE: 0, RZZ_RISE: 9, RZZ_FALL: 19, RZZ_BASE: 0, STB: 14, STB_BASE: 0 }
    TS1 { PRD: 20, NRZ: 1, NRZ_BASE: 0, RZ: 8, RZ_RETURN: 10, RZ_BASE: 0, RZZ_RISE: 9, RZZ_FALL: 19, RZZ_BASE: 0, STB: 14, STB_BASE: 0 }
    TS2 { PRD: 20, NRZ: 1, NRZ_BASE: 0, RZ: 8, RZ_RETURN: 10, RZ_BASE: 0, RZZ_RISE: 9, RZZ_FALL: 19, RZZ_BASE: 0, STB: 14, STB_BASE: 0 }
END
