// Generated by Verilog/pin/gen_pin_adapter.py. Do not edit by hand.

module PinInAdapter(
    input  wire [25:0] PIN_IN,
    output wire CLK,
    output wire RST_N,
    output wire START_IN,
    output wire START_OUT,
    output wire R,
    output wire W,
    output wire [7:0] ADDR,
    output wire DQ_IN,
    output wire [7:0] MR_IN,
    output wire MRW,
    output wire MRR,
    output wire DRIV
);
    assign CLK          = PIN_IN[0];
    assign RST_N        = PIN_IN[1];
    assign START_IN     = PIN_IN[2];
    assign START_OUT    = PIN_IN[3];
    assign R            = PIN_IN[4];
    assign W            = PIN_IN[5];
    assign ADDR         = PIN_IN[13:6];
    assign DQ_IN        = PIN_IN[14];
    assign MR_IN        = PIN_IN[22:15];
    assign MRW          = PIN_IN[23];
    assign MRR          = PIN_IN[24];
    assign DRIV         = PIN_IN[25];

endmodule
