// Generated by Verilog/pin/gen_pin_adapter.py. Do not edit by hand.

module PinInAdapter(
    input  wire [30:0] PIN_IN,
    output wire R,
    output wire W,
    output wire [7:0] ADDR,
    output wire [7:0] DQ_IN,
    output wire [7:0] MR_IN,
    output wire MRW,
    output wire MRR,
    output wire DRIV,
    output wire CLK,
    output wire RST_N
);
    assign R            = PIN_IN[0];
    assign W            = PIN_IN[1];
    assign ADDR         = PIN_IN[9:2];
    assign DQ_IN        = PIN_IN[17:10];
    assign MR_IN        = PIN_IN[25:18];
    assign MRW          = PIN_IN[26];
    assign MRR          = PIN_IN[27];
    assign DRIV         = PIN_IN[28];
    assign CLK          = PIN_IN[29];
    assign RST_N        = PIN_IN[30];

endmodule
