// Generated by Verilog/pin/gen_pin_adapter.py. Do not edit by hand.

module PinOutAdapter(
    input  wire DQ_IE,
    input  wire [7:0] DQ_OUT,
    input  wire [7:0] MR_OUT,
    input  wire DQ_OE,
    input  wire DQ_OUT_VALID,
    output wire [18:0] PIN_OUT
);
    assign PIN_OUT[0]      = DQ_IE;
    assign PIN_OUT[8:1]    = DQ_OUT;
    assign PIN_OUT[16:9]   = MR_OUT;
    assign PIN_OUT[17]     = DQ_OE;
    assign PIN_OUT[18]     = DQ_OUT_VALID;

endmodule
