NOP   :                 ; MRW < 0, 56  ; 
      :                 ;              ;
      : ADDR < 0        ; W < ADDR, D  ;
      : ADDR < ADDR + 1 ; W < ADDR, /D ;
NOP   : ADDR < ADDR + 1 ; W < ADDR, /D ;
      : ADDR < ADDR + 1 ; W < ADDR, /D ;
      : ADDR < 0        ; R < ADDR     ;
      : ADDR < ADDR + 1 ; R < ADDR     ;
NOP   : ADDR < ADDR + 1 ; R < ADDR     ;
      : ADDR < ADDR + 1 ; R < ADDR     ;
      :                 ;              ;
      :                 ;              ;
FOR-12:                 ;              ;
      :                 ;              ;
      :                 ;              ;
      :                 ;              ;
NOP   :                 ; S < I, D     ;
      :                 ; S < I, /D    ;
      :                 ; S < I, /D    ;
      :                 ; S < I, /D    ;
FOR-10:                 ;              ;
      :                 ;              ;
      :                 ;              ;
      :                 ;              ;
