?start: cmd
      | reset
      | compare_all
      | compare_last
      | clear_compare

cmd: NAME DIRECTION cmd_args?
reset: "RST"
compare_all: "CPA"
compare_last: "CPL"
clear_compare: "CCR"

DIRECTION: "<" | ">"
NAME: /[A-Z][A-Z0-9_]*/

?cmd_args: expr ("," expr)*

?expr: term
     | expr "+" term   -> add

?term: HEX           -> hex_lit
     | INT           -> int_lit
     | NAME          -> var

HEX: /0[xX][0-9a-fA-F]+/
%import common.INT
%import common.WS
%ignore WS
