// Generated by Verilog/pin/gen_pin_adapter.py. Do not edit by hand.

module DUT(
    input  wire       CLK,
    input  wire       RST_N,
    input  wire [28:0] IN,
    output wire [18:0] OUT
);
    wire       R;
    wire       W;
    wire [7:0] ADDR;
    wire [7:0] DQ_IN;
    wire [7:0] MR_IN;
    wire       MRW;
    wire       MRR;
    wire       DRIV;

    wire       DQ_IE;
    wire [7:0] DQ_OUT;
    wire [7:0] MR_OUT;
    wire       DQ_OE;
    wire       DQ_OUT_VALID;

    PinInAdapter u_pin_in_adapter (
        .PIN_IN      (IN),
        .R           (R),
        .W           (W),
        .ADDR        (ADDR),
        .DQ_IN       (DQ_IN),
        .MR_IN       (MR_IN),
        .MRW         (MRW),
        .MRR         (MRR),
        .DRIV        (DRIV)
    );

    Dram u_dut (
        .CLK         (CLK),
        .RST_N       (RST_N),
        .R           (R),
        .W           (W),
        .ADDR        (ADDR),
        .DQ_IN       (DQ_IN),
        .MR_IN       (MR_IN),
        .MRW         (MRW),
        .MRR         (MRR),
        .DRIV        (DRIV),
        .DQ_IE       (DQ_IE),
        .DQ_OUT      (DQ_OUT),
        .MR_OUT      (MR_OUT),
        .DQ_OE       (DQ_OE),
        .DQ_OUT_VALID(DQ_OUT_VALID)
    );

    PinOutAdapter u_pin_out_adapter (
        .DQ_IE       (DQ_IE),
        .DQ_OUT      (DQ_OUT),
        .MR_OUT      (MR_OUT),
        .DQ_OE       (DQ_OE),
        .DQ_OUT_VALID(DQ_OUT_VALID),
        .PIN_OUT     (OUT)
    );

endmodule
