// Generated by Verilog/pin/gen_pin_adapter.py. Do not edit by hand.

module DUT #(
    parameter VOLTAGE_W = 32
)(
    /* verilator lint_off UNUSEDSIGNAL */
    input  wire ATE_CLK,
    input  wire ATE_RST_N,
    input  wire DUT_ANALOG_ENABLE,
    /* verilator lint_on UNUSEDSIGNAL */
    input  wire [23:0] IN,
    input  wire [23:0] DUT_INPUT_ENABLE,
    input  wire [24*VOLTAGE_W-1:0] ATE_PIN_IN_UV,
    input  wire [24*VOLTAGE_W-1:0] DUT_INPUT_RISE_STEP_UV,
    input  wire [24*VOLTAGE_W-1:0] DUT_INPUT_FALL_STEP_UV,
    input  wire [3:0] DUT_RX_DQS_SKEW,
    input  wire [3:0] DUT_RX_DQ_SKEW,
    input  wire [3:0] DUT_TX_DQS_SKEW,
    input  wire [3:0] DUT_TX_DQ_SKEW,
    input  wire [4:0] DUT_OUTPUT_ENABLE,
    input  wire [5*VOLTAGE_W-1:0] DUT_LOW_UV,
    input  wire [5*VOLTAGE_W-1:0] DUT_HIGH_UV,
    input  wire [5*VOLTAGE_W-1:0] DUT_RISE_STEP_UV,
    input  wire [5*VOLTAGE_W-1:0] DUT_FALL_STEP_UV,
    input  wire [VOLTAGE_W-1:0] DUT_VDDQ_UV,
    output wire [4:0] OUT,
    output wire [24*VOLTAGE_W-1:0] PIN_IN_UV,
    output wire [5*VOLTAGE_W-1:0] PIN_OUT_UV
);
    wire [4:0] dut_output;
    wire       CLK;
    wire       RST_N;
    wire       R;
    wire       W;
    wire [7:0] ADDR;
    wire       DQ_RX_BIT;
    wire       DQS_RX_BIT;
    wire [7:0] MR_IN;
    wire       MRW;
    wire       MRR;

    wire       DQ_IE;
    wire       DQ_TX_BIT;
    wire       DQS_TX_BIT;
    wire       DQ_OE;
    wire       DQ_OUT_VALID;

    PinInAdapter u_pin_in_adapter (
        .PIN_IN      (IN),
        .CLK         (CLK),
        .RST_N       (RST_N),
        .R           (R),
        .W           (W),
        .ADDR        (ADDR),
        .DQ_RX_BIT   (DQ_RX_BIT),
        .DQS_RX_BIT  (DQS_RX_BIT),
        .MR_IN       (MR_IN),
        .MRW         (MRW),
        .MRR         (MRR)
    );

    ChipAnalogWrapper u_dut (
        .CLK         (CLK),
        .RST_N       (RST_N),
        .R           (R),
        .W           (W),
        .ADDR        (ADDR),
        .DQ_RX_BIT   (DQ_RX_BIT),
        .DQS_RX_BIT  (DQS_RX_BIT),
        .MR_IN       (MR_IN),
        .MRW         (MRW),
        .MRR         (MRR),
        .DQ_IE       (DQ_IE),
        .DQ_TX_BIT   (DQ_TX_BIT),
        .DQS_TX_BIT  (DQS_TX_BIT),
        .DQ_OE       (DQ_OE),
        .DQ_OUT_VALID(DQ_OUT_VALID),
        .VDDQ_UV     (DUT_VDDQ_UV),
        .ANALOG_ENABLE(DUT_ANALOG_ENABLE),
        .ATE_CLK     (ATE_CLK),
        .ATE_PIN_IN_UV(ATE_PIN_IN_UV),
        .DUT_INPUT_ENABLE(DUT_INPUT_ENABLE),
        .DUT_INPUT_RISE_STEP_UV(DUT_INPUT_RISE_STEP_UV),
        .DUT_INPUT_FALL_STEP_UV(DUT_INPUT_FALL_STEP_UV),
        .DUT_RX_DQS_SKEW(DUT_RX_DQS_SKEW),
        .DUT_RX_DQ_SKEW(DUT_RX_DQ_SKEW),
        .DUT_TX_DQS_SKEW(DUT_TX_DQS_SKEW),
        .DUT_TX_DQ_SKEW(DUT_TX_DQ_SKEW),
        .DUT_OUTPUT_ENABLE(DUT_OUTPUT_ENABLE),
        .DUT_LOW_UV  (DUT_LOW_UV),
        .DUT_HIGH_UV (DUT_HIGH_UV),
        .DUT_RISE_STEP_UV(DUT_RISE_STEP_UV),
        .DUT_FALL_STEP_UV(DUT_FALL_STEP_UV),
        .PIN_IN_UV   (PIN_IN_UV),
        .PIN_OUT_UV  (PIN_OUT_UV)
    );

    PinOutAdapter u_pin_out_adapter (
        .DQ_IE       (DQ_IE),
        .DQ_TX_BIT   (DQ_TX_BIT),
        .DQS_TX_BIT  (DQS_TX_BIT),
        .DQ_OE       (DQ_OE),
        .DQ_OUT_VALID(DQ_OUT_VALID),
        .PIN_OUT     (dut_output)
    );

    assign OUT = dut_output;

endmodule
