            CTRL        |    REG     :                CMD             ;// This is a comment
            -----------------------------------------------------
START#      FOR-2       |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            NOP         | ADDR =  0  : MRW < ADDR, 56  ;              ; 
                        | ADDR =  1  : MRW < ADDR, 54  ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            FOR-0       |            :                 ;              ;// This is a comment
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            NOP         |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        | ADDR =  0  : WR < ADDR       ;              ;
            FOR-5       |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            NOP         |            :                 ; DRV < X      ;
                        |            :                 ; DRV < X, T   ;
                        |            :                 ; DRV < X      ;
                        |            :                 ; DRV < X, T   ;
            FOR-2       |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            GOTO-0 STOP |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            NOP         |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        | ADDR =  0  : RD < ADDR       ;              ;
            FOR-6       |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            NOP         |            :                 ; SMP < Y      ;
                        |            :                 ; SMP < Y, T   ;
                        |            :                 ; SMP < Y      ;
                        |            :                 ; SMP < Y, T   ;
            GOTO-4 START|            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
STOP#       FOR-6       |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
                        |            :                 ;              ;
            -----------------------------------------------------