"""
pybind11 ate class
"""
from __future__ import annotations
__all__: list[str] = ['ATE']
class ATE:
    def __init__(self, wave_name: str, trace_enable: bool, top_data_init: int) -> None:
        ...
    def clock(self) -> int:
        ...
    def compare(self) -> None:
        ...
    def drive(self, offset: int, inverted: bool) -> None:
        ...
    def mr_read(self, addr: int) -> None:
        ...
    def mr_write(self, addr: int, mr_data: int) -> None:
        ...
    def read(self, addr: int) -> None:
        ...
    def sample(self, offset: int, inverted: bool) -> None:
        ...
    def set_top_data(self, data: int) -> None:
        ...
    def tick(self) -> None:
        ...
    def top_data(self) -> int:
        ...
    def write(self, addr: int) -> None:
        ...
