"""
pybind11 ate class
"""
from __future__ import annotations
import typing
__all__: list[str] = ['ATE']
class ATE:
    def __init__(self, wave_name: str, trace_enable: bool, top_data_init: typing.SupportsInt) -> None:
        ...
    def clock(self) -> int:
        ...
    def compare(self) -> None:
        ...
    def drive(self, offset: typing.SupportsInt, inverted: bool) -> None:
        ...
    def mr_read(self, addr: typing.SupportsInt) -> None:
        ...
    def mr_write(self, addr: typing.SupportsInt, mr_data: typing.SupportsInt) -> None:
        ...
    def read(self, addr: typing.SupportsInt) -> None:
        ...
    def sample(self, offset: typing.SupportsInt, inverted: bool) -> None:
        ...
    def set_top_data(self, data: typing.SupportsInt) -> None:
        ...
    def tick(self) -> None:
        ...
    def top_data(self) -> int:
        ...
    def write(self, addr: typing.SupportsInt) -> None:
        ...
